// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dedup_links
NumericMatrix dedup_links(NumericMatrix links);
RcppExport SEXP _FastPG_dedup_links(SEXP linksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type links(linksSEXP);
    rcpp_result_gen = Rcpp::wrap(dedup_links(links));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_jce
NumericMatrix rcpp_parallel_jce(NumericMatrix mat);
RcppExport SEXP _FastPG_rcpp_parallel_jce(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_jce(mat));
    return rcpp_result_gen;
END_RCPP
}
// parallel_louvain
Rcpp::List parallel_louvain(NumericMatrix links, int minGraphSize, double C_thresh, double threshold, int numColors, int coloring, int syncType, int basicOpt);
RcppExport SEXP _FastPG_parallel_louvain(SEXP linksSEXP, SEXP minGraphSizeSEXP, SEXP C_threshSEXP, SEXP thresholdSEXP, SEXP numColorsSEXP, SEXP coloringSEXP, SEXP syncTypeSEXP, SEXP basicOptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type links(linksSEXP);
    Rcpp::traits::input_parameter< int >::type minGraphSize(minGraphSizeSEXP);
    Rcpp::traits::input_parameter< double >::type C_thresh(C_threshSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type numColors(numColorsSEXP);
    Rcpp::traits::input_parameter< int >::type coloring(coloringSEXP);
    Rcpp::traits::input_parameter< int >::type syncType(syncTypeSEXP);
    Rcpp::traits::input_parameter< int >::type basicOpt(basicOptSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_louvain(links, minGraphSize, C_thresh, threshold, numColors, coloring, syncType, basicOpt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastPG_dedup_links", (DL_FUNC) &_FastPG_dedup_links, 1},
    {"_FastPG_rcpp_parallel_jce", (DL_FUNC) &_FastPG_rcpp_parallel_jce, 1},
    {"_FastPG_parallel_louvain", (DL_FUNC) &_FastPG_parallel_louvain, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastPG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
