# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_parallel_jce <- function(mat) {
    .Call(`_rgrappolo_rcpp_parallel_jce`, mat)
}

parallel_louvain <- function(links, num_vertices) {
    .Call(`_rgrappolo_parallel_louvain`, links, num_vertices)
}

