# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove duplicate links
#'
#' @param links A numeric matrix of network edges
#' @return The matrix of edges with duplicates removed
#' @export
dedup_links <- function(links) {
    .Call(`_FastPG_dedup_links`, links)
}

#' Parallel Jaccard similarity index
#'
#' @param mat A numeric matrix of values
#' @return A numeric matrix of values
#' @export
rcpp_parallel_jce <- function(mat) {
    .Call(`_FastPG_rcpp_parallel_jce`, mat)
}

#' Parallel Louvain clustering
#'
#' @param links A numeric matrix of network edges
#' @return A list with two elements
#' * `modularity` - 
#' * `communities` - A vector where the i'th value is the
#'   cluster number that the i'th node in the links matrix has been assigned to.
#' @export
parallel_louvain <- function(links, minGraphSize = 1000L, C_thresh = 0.000001, threshold = 0.000000001, numColors = 16L, strongScaling = FALSE, coloring = 1L, syncType = 0L, basicOpt = 1L) {
    .Call(`_FastPG_parallel_louvain`, links, minGraphSize, C_thresh, threshold, numColors, strongScaling, coloring, syncType, basicOpt)
}

